### ISSUE TITLE
Latest release for v4 missing the latest changes

### ISSUE THREAD

**Issue by andres-movl** [mgugger/actix-web-sample-app#2]
When will HEAD be launched to a new released? Currently cloning the whole repo to get the latest changes to remove the AppState traits.

**Comment by mgugger** [comment]
Hi Andres

I hadn't yet time to finish implementing the custom filters. I will create a new 0.5 release once this done, hopefully I'll find time in the next few days.

Sorry for the inconvenience with the removed AppState traits, cloning the repo directly is indeed the best option for the moment until the next release.
