### ISSUE TITLE
Templates not rendering because of navbar_title

### ISSUE THREAD

**Issue by andres-movl** [mgugger/actix-web-sample-app#3]
I've been trying to follow the code, but a bit lost. I'm sure I'm setting the navbar_title in the configuration but the 'head' template fails to render all the time because of missing navbar_title in the context

**Comment by mgugger** [comment]
Hi Andres

I couldn't reproduce the issue and it works in the tests and in the example. Can you share what you did and where it's failing for you?

**Comment by andres-movl** [comment]
sure, so here's my config function:
`fn create_actix_admin_builder() -> ActixAdminBuilder {
    let configuration = ActixAdminConfiguration {
        enable_auth: false,
        user_is_logged_in: None,
        login_link: None,
        logout_link: None,
        file_upload_directory: "./file_uploads",
        navbar_title: "OpenSun"
    };

    let mut admin_builder = ActixAdminBuilder::new(configuration);
    
    let unit_view_model = ActixAdminViewModel::from(entities::unit::Entity);
    admin_builder.add_entity::<entities::unit::Entity>(&unit_view_model);

    let user_view_model = ActixAdminViewModel::from(entities::auth_user::Entity);
    admin_builder.add_entity::<entities::auth_user::Entity>(&user_view_model);

    admin_builder
}`


And this is my "main":


`env_logger::init_from_env(env_logger::Env::new().default_filter_or("debug"));

    let server = HttpServer::new(move || {
        let actix_admin_builder = create_actix_admin_builder();

        App::new()
            .app_data(Data::new(conn.clone()))
            .app_data(Data::new(redis_pool.clone()))
            .app_data(Data::new(actix_admin_builder.get_actix_admin()))
            .service(actix_admin_builder.get_scope())
            .service(get_asset_availability)
            .service(create_reservation)
            .wrap(Logger::default())
    })
    .bind(("0.0.0.0", 8080))?
    .run();`
    
    Let me know if you think it could have something to do with the Sea ORM entities too.

**Comment by mgugger** [comment]
thanks for the code example! Looks good to me...

I have published 0.5.0, can you try whether this fixes the issue for you?
```rust
actix-admin = "0.5.0"
```
I took your code example it works for me in the example below. Do you spot any differences (besides no redis pool) ?
https://github.com/mgugger/actix-admin-example

**Comment by andres-movl** [comment]
Awesome, it works now well thanks. Not sure what it was, but pulled the latest changes and now works fine. I'll be closing the issue.
